### ISSUE TITLE
Power Off completely via reed-switch for very long standby

### ISSUE THREAD

**Issue by heeplr** [johan-m-o/BikeTracker#2]
This is a cool project, thanks for sharing it.

Do you think it'd be possible to only use the circuit in "armed" mode, by using a reed switch + magnet to disconnect the battery?
If that would work, the battery should last very long (e.g. when keeping the bike in a locked room) and could be armed simply by removing the magnet.

Can you come up with any reason, why that's a stupid idea?

**Comment by johan-m-o** [comment]
Thank you, glad to have let people take part of it.

That's exactly what the included switch is for. It breaks the connection between the battery and the microcontroller, so that no power is drawn when using the bike or storing it somewhere you're fairly sure it won't be stolen.

But yeah, using a reed switch and a magnet could make that automatic, by having the magnet placed so that it breaks the connection whenever you place the bike in a stand or similar. Cool idea with lots of expanded possibilities.
